#############################################################################
# Makefile for building: linux-bin/qt-wspr
# Generated by qmake (3.1) (Qt 5.15.10)
# Project:  qt-wspr.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile qt-wspr.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DGITHASH=\"------\" -DHAVE_SDRPLAY_V3 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -fsanitize=address -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++14 -g -fsanitize=address -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Ifilters -Iwsprd -Iutils -Iutils/kiss -Iscopes-qwt6 -Idevices -I/usr/include/qt5/qwt -Idevices/sdrplay-handler-v3 -Idevices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I/../lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qt-wspr1.0.0
DISTDIR = /home/jan/qt-wspr/.tmp/qt-wspr1.0.0
LINK          = g++
LFLAGS        = -g -fsanitize=address -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib64 -L/lib64 -lqwt-qt5 -lrt -lsndfile -lsamplerate -lportaudio -lusb-1.0 -lfftw3f -ldl /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		radio.cpp \
		decoder.cpp \
		utils/decimator.cpp \
		utils/kiss/kiss_fft.c \
		utils/kiss/kiss_fftr.c \
		filters/fir-filters.cpp \
		scopes-qwt6/virtual-scope.cpp \
		scopes-qwt6/waterfall-scope.cpp \
		scopes-qwt6/spectrum-scope.cpp \
		scopes-qwt6/scope.cpp \
		scopes-qwt6/fft-scope.cpp \
		wsprd/fano.cpp \
		wsprd/nhash.cpp \
		wsprd/tab.cpp \
		wsprd/wsprd.cpp \
		wsprd/wsprd_utils.cpp \
		wsprd/wsprsim_utils.cpp \
		devices/deviceselect.cpp \
		devices/device-handler.cpp \
		devices/sdrplay-handler-v3/Rsp-device.cpp \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp \
		devices/sdrplay-handler-v3/Rsp1A-handler.cpp \
		devices/sdrplay-handler-v3/RspII-handler.cpp \
		devices/sdrplay-handler-v3/RspDuo-handler.cpp \
		devices/sdrplay-handler-v3/RspDx-handler.cpp qrc_resources.cpp \
		moc_radio.cpp \
		moc_decoder.cpp \
		moc_virtual-scope.cpp \
		moc_waterfall-scope.cpp \
		moc_spectrum-scope.cpp \
		moc_scope.cpp \
		moc_fft-scope.cpp \
		moc_deviceselect.cpp \
		moc_device-handler.cpp \
		moc_sdrplay-handler-v3.cpp \
		moc_Rsp-device.cpp
OBJECTS       = main.o \
		radio.o \
		decoder.o \
		decimator.o \
		kiss_fft.o \
		kiss_fftr.o \
		fir-filters.o \
		virtual-scope.o \
		waterfall-scope.o \
		spectrum-scope.o \
		scope.o \
		fft-scope.o \
		fano.o \
		nhash.o \
		tab.o \
		wsprd.o \
		wsprd_utils.o \
		wsprsim_utils.o \
		deviceselect.o \
		device-handler.o \
		Rsp-device.o \
		sdrplay-handler-v3.o \
		Rsp1A-handler.o \
		RspII-handler.o \
		RspDuo-handler.o \
		RspDx-handler.o \
		qrc_resources.o \
		moc_radio.o \
		moc_decoder.o \
		moc_virtual-scope.o \
		moc_waterfall-scope.o \
		moc_spectrum-scope.o \
		moc_scope.o \
		moc_fft-scope.o \
		moc_deviceselect.o \
		moc_device-handler.o \
		moc_sdrplay-handler-v3.o \
		moc_Rsp-device.o
DIST          = /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/uic.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		qt-wspr.pro constants.h \
		radio.h \
		decoder.h \
		utils/ringbuffer.h \
		utils/decimator.h \
		utils/kiss/kiss_fft.h \
		utils/kiss/kiss_fftr.h \
		utils/kiss/_kiss_fft_guts.h \
		filters/fir-filters.h \
		scopes-qwt6/virtual-scope.h \
		scopes-qwt6/spectrogramdata.h \
		scopes-qwt6/waterfall-scope.h \
		scopes-qwt6/spectrum-scope.h \
		scopes-qwt6/scope.h \
		scopes-qwt6/fft-scope.h \
		wsprd/fano.h \
		wsprd/metric_tables.h \
		wsprd/nhash.h \
		wsprd/wsprd.h \
		wsprd/wsprd_utils.h \
		wsprd/wsprsim_utils.h \
		devices/deviceselect.h \
		devices/device-handler.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		devices/sdrplay-handler-v3/sdrplay-commands.h \
		devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/Rsp1A-handler.h \
		devices/sdrplay-handler-v3/RspII-handler.h \
		devices/sdrplay-handler-v3/RspDuo-handler.h \
		devices/sdrplay-handler-v3/RspDx-handler.h main.cpp \
		radio.cpp \
		decoder.cpp \
		utils/decimator.cpp \
		utils/kiss/kiss_fft.c \
		utils/kiss/kiss_fftr.c \
		filters/fir-filters.cpp \
		scopes-qwt6/virtual-scope.cpp \
		scopes-qwt6/waterfall-scope.cpp \
		scopes-qwt6/spectrum-scope.cpp \
		scopes-qwt6/scope.cpp \
		scopes-qwt6/fft-scope.cpp \
		wsprd/fano.cpp \
		wsprd/nhash.cpp \
		wsprd/tab.cpp \
		wsprd/wsprd.cpp \
		wsprd/wsprd_utils.cpp \
		wsprd/wsprsim_utils.cpp \
		devices/deviceselect.cpp \
		devices/device-handler.cpp \
		devices/sdrplay-handler-v3/Rsp-device.cpp \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp \
		devices/sdrplay-handler-v3/Rsp1A-handler.cpp \
		devices/sdrplay-handler-v3/RspII-handler.cpp \
		devices/sdrplay-handler-v3/RspDuo-handler.cpp \
		devices/sdrplay-handler-v3/RspDx-handler.cpp
QMAKE_TARGET  = qt-wspr
DESTDIR       = linux-bin/
TARGET        = linux-bin/qt-wspr


first: all
####### Build rules

linux-bin/qt-wspr: ui_newradio.h ui_sdrplay-widget-v3.h $(OBJECTS)  
	@test -d linux-bin/ || mkdir -p linux-bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt-wspr.pro /../lib64/qt5/mkspecs/linux-g++/qmake.conf /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/uic.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		qt-wspr.pro \
		resources.qrc
	$(QMAKE) -o Makefile qt-wspr.pro
/../lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/../lib64/qt5/mkspecs/qconfig.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/../lib64/qt5/mkspecs/features/qt_functions.prf:
/../lib64/qt5/mkspecs/features/qt_config.prf:
/../lib64/qt5/mkspecs/linux-g++/qmake.conf:
/../lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/../lib64/qt5/mkspecs/features/exclusive_builds.prf:
/../lib64/qt5/mkspecs/features/toolchain.prf:
/../lib64/qt5/mkspecs/features/default_pre.prf:
/../lib64/qt5/mkspecs/features/resolve_config.prf:
/../lib64/qt5/mkspecs/features/default_post.prf:
/../lib64/qt5/mkspecs/features/warn_on.prf:
/../lib64/qt5/mkspecs/features/qt.prf:
/../lib64/qt5/mkspecs/features/resources_functions.prf:
/../lib64/qt5/mkspecs/features/resources.prf:
/../lib64/qt5/mkspecs/features/moc.prf:
/../lib64/qt5/mkspecs/features/unix/opengl.prf:
/../lib64/qt5/mkspecs/features/uic.prf:
/../lib64/qt5/mkspecs/features/unix/thread.prf:
/../lib64/qt5/mkspecs/features/qmake_use.prf:
/../lib64/qt5/mkspecs/features/file_copies.prf:
/../lib64/qt5/mkspecs/features/testcase_targets.prf:
/../lib64/qt5/mkspecs/features/exceptions.prf:
/../lib64/qt5/mkspecs/features/yacc.prf:
/../lib64/qt5/mkspecs/features/lex.prf:
qt-wspr.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile qt-wspr.pro

qmake_all: FORCE


all: Makefile linux-bin/qt-wspr

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /../lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents constants.h radio.h decoder.h utils/ringbuffer.h utils/decimator.h utils/kiss/kiss_fft.h utils/kiss/kiss_fftr.h utils/kiss/_kiss_fft_guts.h filters/fir-filters.h scopes-qwt6/virtual-scope.h scopes-qwt6/spectrogramdata.h scopes-qwt6/waterfall-scope.h scopes-qwt6/spectrum-scope.h scopes-qwt6/scope.h scopes-qwt6/fft-scope.h wsprd/fano.h wsprd/metric_tables.h wsprd/nhash.h wsprd/wsprd.h wsprd/wsprd_utils.h wsprd/wsprsim_utils.h devices/deviceselect.h devices/device-handler.h devices/sdrplay-handler-v3/sdrplay-handler-v3.h devices/sdrplay-handler-v3/sdrplay-commands.h devices/sdrplay-handler-v3/Rsp-device.h devices/sdrplay-handler-v3/Rsp1A-handler.h devices/sdrplay-handler-v3/RspII-handler.h devices/sdrplay-handler-v3/RspDuo-handler.h devices/sdrplay-handler-v3/RspDx-handler.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp radio.cpp decoder.cpp utils/decimator.cpp utils/kiss/kiss_fft.c utils/kiss/kiss_fftr.c filters/fir-filters.cpp scopes-qwt6/virtual-scope.cpp scopes-qwt6/waterfall-scope.cpp scopes-qwt6/spectrum-scope.cpp scopes-qwt6/scope.cpp scopes-qwt6/fft-scope.cpp wsprd/fano.cpp wsprd/nhash.cpp wsprd/tab.cpp wsprd/wsprd.cpp wsprd/wsprd_utils.cpp wsprd/wsprsim_utils.cpp devices/deviceselect.cpp devices/device-handler.cpp devices/sdrplay-handler-v3/Rsp-device.cpp devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp devices/sdrplay-handler-v3/Rsp1A-handler.cpp devices/sdrplay-handler-v3/RspII-handler.cpp devices/sdrplay-handler-v3/RspDuo-handler.cpp devices/sdrplay-handler-v3/RspDx-handler.cpp $(DISTDIR)/
	$(COPY_FILE) --parents newradio.ui devices/sdrplay-handler-v3/sdrplay-widget-v3.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/../lib64/qt5/bin/rcc \
		qt-wspr.ico \
		AUTHORS \
		COPYING
	/../lib64/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /../lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++14 -g -fsanitize=address -O2 -Wall -Wextra -dM -E -o moc_predefs.h /../lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_radio.cpp moc_decoder.cpp moc_virtual-scope.cpp moc_waterfall-scope.cpp moc_spectrum-scope.cpp moc_scope.cpp moc_fft-scope.cpp moc_deviceselect.cpp moc_device-handler.cpp moc_sdrplay-handler-v3.cpp moc_Rsp-device.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_radio.cpp moc_decoder.cpp moc_virtual-scope.cpp moc_waterfall-scope.cpp moc_spectrum-scope.cpp moc_scope.cpp moc_fft-scope.cpp moc_deviceselect.cpp moc_device-handler.cpp moc_sdrplay-handler-v3.cpp moc_Rsp-device.cpp
moc_radio.cpp: radio.h \
		ui_newradio.h \
		constants.h \
		utils/ringbuffer.h \
		filters/fir-filters.h \
		utils/decimator.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include radio.h -o moc_radio.cpp

moc_decoder.cpp: decoder.h \
		constants.h \
		utils/ringbuffer.h \
		wsprd/wsprd.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include decoder.h -o moc_decoder.cpp

moc_virtual-scope.cpp: scopes-qwt6/virtual-scope.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include scopes-qwt6/virtual-scope.h -o moc_virtual-scope.cpp

moc_waterfall-scope.cpp: scopes-qwt6/waterfall-scope.h \
		scopes-qwt6/virtual-scope.h \
		scopes-qwt6/spectrogramdata.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include scopes-qwt6/waterfall-scope.h -o moc_waterfall-scope.cpp

moc_spectrum-scope.cpp: scopes-qwt6/spectrum-scope.h \
		scopes-qwt6/virtual-scope.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include scopes-qwt6/spectrum-scope.h -o moc_spectrum-scope.cpp

moc_scope.cpp: scopes-qwt6/scope.h \
		constants.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include scopes-qwt6/scope.h -o moc_scope.cpp

moc_fft-scope.cpp: scopes-qwt6/fft-scope.h \
		scopes-qwt6/virtual-scope.h \
		utils/kiss/kiss_fft.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include scopes-qwt6/fft-scope.h -o moc_fft-scope.cpp

moc_deviceselect.cpp: devices/deviceselect.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include devices/deviceselect.h -o moc_deviceselect.cpp

moc_device-handler.cpp: devices/device-handler.h \
		constants.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include devices/device-handler.h -o moc_device-handler.cpp

moc_sdrplay-handler-v3.cpp: devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include devices/sdrplay-handler-v3/sdrplay-handler-v3.h -o moc_sdrplay-handler-v3.cpp

moc_Rsp-device.cpp: devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/qt-wspr/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/qt-wspr -I/home/jan/qt-wspr -I/home/jan/qt-wspr/filters -I/home/jan/qt-wspr/wsprd -I/home/jan/qt-wspr/utils -I/home/jan/qt-wspr/utils/kiss -I/home/jan/qt-wspr/scopes-qwt6 -I/home/jan/qt-wspr/devices -I/usr/include/qt5/qwt -I/home/jan/qt-wspr/devices/sdrplay-handler-v3 -I/home/jan/qt-wspr/devices/sdrplay-handler-v3/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/c++/13/x86_64-redhat-linux -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-redhat-linux/13/include -I/usr/local/include -I/usr/include devices/sdrplay-handler-v3/Rsp-device.h -o moc_Rsp-device.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_newradio.h ui_sdrplay-widget-v3.h
compiler_uic_clean:
	-$(DEL_FILE) ui_newradio.h ui_sdrplay-widget-v3.h
ui_newradio.h: newradio.ui \
		/../lib64/qt5/bin/uic \
		/usr/include/qt5/qwt/qwt_plot.h
	/../lib64/qt5/bin/uic newradio.ui -o ui_newradio.h

ui_sdrplay-widget-v3.h: devices/sdrplay-handler-v3/sdrplay-widget-v3.ui \
		/../lib64/qt5/bin/uic
	/../lib64/qt5/bin/uic devices/sdrplay-handler-v3/sdrplay-widget-v3.ui -o ui_sdrplay-widget-v3.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp radio.h \
		ui_newradio.h \
		constants.h \
		utils/ringbuffer.h \
		filters/fir-filters.h \
		utils/decimator.h \
		Combinear.qss
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

radio.o: radio.cpp constants.h \
		radio.h \
		ui_newradio.h \
		utils/ringbuffer.h \
		filters/fir-filters.h \
		utils/decimator.h \
		scopes-qwt6/fft-scope.h \
		scopes-qwt6/virtual-scope.h \
		utils/kiss/kiss_fft.h \
		decoder.h \
		wsprd/wsprd.h \
		devices/device-handler.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		ui_sdrplay-widget-v3.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radio.o radio.cpp

decoder.o: decoder.cpp decoder.h \
		constants.h \
		utils/ringbuffer.h \
		wsprd/wsprd.h \
		radio.h \
		ui_newradio.h \
		filters/fir-filters.h \
		utils/decimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decoder.o decoder.cpp

decimator.o: utils/decimator.cpp utils/decimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decimator.o utils/decimator.cpp

kiss_fft.o: utils/kiss/kiss_fft.c utils/kiss/_kiss_fft_guts.h \
		utils/kiss/kiss_fft.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o kiss_fft.o utils/kiss/kiss_fft.c

kiss_fftr.o: utils/kiss/kiss_fftr.c utils/kiss/kiss_fftr.h \
		utils/kiss/kiss_fft.h \
		utils/kiss/_kiss_fft_guts.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o kiss_fftr.o utils/kiss/kiss_fftr.c

fir-filters.o: filters/fir-filters.cpp filters/fir-filters.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fir-filters.o filters/fir-filters.cpp

virtual-scope.o: scopes-qwt6/virtual-scope.cpp scopes-qwt6/virtual-scope.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o virtual-scope.o scopes-qwt6/virtual-scope.cpp

waterfall-scope.o: scopes-qwt6/waterfall-scope.cpp scopes-qwt6/waterfall-scope.h \
		scopes-qwt6/virtual-scope.h \
		scopes-qwt6/spectrogramdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waterfall-scope.o scopes-qwt6/waterfall-scope.cpp

spectrum-scope.o: scopes-qwt6/spectrum-scope.cpp scopes-qwt6/spectrum-scope.h \
		scopes-qwt6/virtual-scope.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectrum-scope.o scopes-qwt6/spectrum-scope.cpp

scope.o: scopes-qwt6/scope.cpp scopes-qwt6/scope.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scope.o scopes-qwt6/scope.cpp

fft-scope.o: scopes-qwt6/fft-scope.cpp scopes-qwt6/spectrum-scope.h \
		scopes-qwt6/virtual-scope.h \
		scopes-qwt6/waterfall-scope.h \
		scopes-qwt6/spectrogramdata.h \
		scopes-qwt6/fft-scope.h \
		utils/kiss/kiss_fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fft-scope.o scopes-qwt6/fft-scope.cpp

fano.o: wsprd/fano.cpp wsprd/fano.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fano.o wsprd/fano.cpp

nhash.o: wsprd/nhash.cpp wsprd/nhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nhash.o wsprd/nhash.cpp

tab.o: wsprd/tab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tab.o wsprd/tab.cpp

wsprd.o: wsprd/wsprd.cpp utils/kiss/kiss_fft.h \
		wsprd/wsprd.h \
		constants.h \
		wsprd/fano.h \
		wsprd/nhash.h \
		wsprd/wsprd_utils.h \
		wsprd/wsprsim_utils.h \
		wsprd/metric_tables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wsprd.o wsprd/wsprd.cpp

wsprd_utils.o: wsprd/wsprd_utils.cpp wsprd/nhash.h \
		wsprd/wsprd_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wsprd_utils.o wsprd/wsprd_utils.cpp

wsprsim_utils.o: wsprd/wsprsim_utils.cpp wsprd/wsprsim_utils.h \
		wsprd/wsprd_utils.h \
		wsprd/nhash.h \
		wsprd/fano.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wsprsim_utils.o wsprd/wsprsim_utils.cpp

deviceselect.o: devices/deviceselect.cpp devices/deviceselect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deviceselect.o devices/deviceselect.cpp

device-handler.o: devices/device-handler.cpp devices/device-handler.h \
		constants.h \
		radio.h \
		ui_newradio.h \
		utils/ringbuffer.h \
		filters/fir-filters.h \
		utils/decimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o device-handler.o devices/device-handler.cpp

Rsp-device.o: devices/sdrplay-handler-v3/Rsp-device.cpp devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rsp-device.o devices/sdrplay-handler-v3/Rsp-device.cpp

sdrplay-handler-v3.o: devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		devices/sdrplay-handler-v3/sdrplay-commands.h \
		devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/Rsp1A-handler.h \
		devices/sdrplay-handler-v3/RspII-handler.h \
		devices/sdrplay-handler-v3/RspDuo-handler.h \
		devices/sdrplay-handler-v3/RspDx-handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sdrplay-handler-v3.o devices/sdrplay-handler-v3/sdrplay-handler-v3.cpp

Rsp1A-handler.o: devices/sdrplay-handler-v3/Rsp1A-handler.cpp devices/sdrplay-handler-v3/Rsp1A-handler.h \
		devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rsp1A-handler.o devices/sdrplay-handler-v3/Rsp1A-handler.cpp

RspII-handler.o: devices/sdrplay-handler-v3/RspII-handler.cpp devices/sdrplay-handler-v3/RspII-handler.h \
		devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RspII-handler.o devices/sdrplay-handler-v3/RspII-handler.cpp

RspDuo-handler.o: devices/sdrplay-handler-v3/RspDuo-handler.cpp devices/sdrplay-handler-v3/RspDuo-handler.h \
		devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RspDuo-handler.o devices/sdrplay-handler-v3/RspDuo-handler.cpp

RspDx-handler.o: devices/sdrplay-handler-v3/RspDx-handler.cpp devices/sdrplay-handler-v3/RspDx-handler.h \
		devices/sdrplay-handler-v3/Rsp-device.h \
		devices/sdrplay-handler-v3/include/sdrplay_api.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_dev.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp1a.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rsp2.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDuo.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rspDx.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_tuner.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_rx_channel.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_control.h \
		devices/sdrplay-handler-v3/include/sdrplay_api_callback.h \
		devices/sdrplay-handler-v3/sdrplay-handler-v3.h \
		utils/decimator.h \
		utils/ringbuffer.h \
		devices/device-handler.h \
		constants.h \
		ui_sdrplay-widget-v3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RspDx-handler.o devices/sdrplay-handler-v3/RspDx-handler.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_radio.o: moc_radio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_radio.o moc_radio.cpp

moc_decoder.o: moc_decoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_decoder.o moc_decoder.cpp

moc_virtual-scope.o: moc_virtual-scope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_virtual-scope.o moc_virtual-scope.cpp

moc_waterfall-scope.o: moc_waterfall-scope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waterfall-scope.o moc_waterfall-scope.cpp

moc_spectrum-scope.o: moc_spectrum-scope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spectrum-scope.o moc_spectrum-scope.cpp

moc_scope.o: moc_scope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scope.o moc_scope.cpp

moc_fft-scope.o: moc_fft-scope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fft-scope.o moc_fft-scope.cpp

moc_deviceselect.o: moc_deviceselect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_deviceselect.o moc_deviceselect.cpp

moc_device-handler.o: moc_device-handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_device-handler.o moc_device-handler.cpp

moc_sdrplay-handler-v3.o: moc_sdrplay-handler-v3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sdrplay-handler-v3.o moc_sdrplay-handler-v3.cpp

moc_Rsp-device.o: moc_Rsp-device.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Rsp-device.o moc_Rsp-device.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

